{% set name = "trio-asyncio" %}
{% set version = "0.14.1" %}
{% set build_num = 5 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trio_asyncio/trio_asyncio-{{ version }}.tar.gz
  sha256: 558e9fd4f6fe7f3809382ea1778d34104726435d86adc91097a7c2c163235dcb

build:
  noarch: python
  number: {{ build_num }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pytest-runner
    - pip
  run:
    - python >=3.8
    - greenlet
    - outcome
    - sniffio >=1.3.0
    - trio >=0.22.0
    - exceptiongroup >=1.0.0

test:
  imports:
    - trio_asyncio

outputs:
  - name: trio-asyncio
  - name: trio_asyncio
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - trio-asyncio ={{ version }}=*_{{ build_num }}
    test:
      imports:
        - trio_asyncio


about:
  home: https://github.com/python-trio/trio-asyncio
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT
  summary: A re-implementation of the asyncio mainloop on top of Trio
  description: |
    Trio has native concepts of tasks and task cancellation. Asyncio is based on
    callbacks and chaining Futures, albeit with nicer syntax, which make handling
    of failures and timeouts fundamentally less reliable, esp. in larger programs.
    Thus, you really want to base your async project on Trio. On the other hand,
    there are quite a few asyncio-enhanced libraries. You really don't want to
    re-invent any wheels in your project. Thus, being able to use asyncio
    libraries from Trio is useful. Trio-Asyncio enables you to do that, and more.
  doc_url: http://trio-asyncio.readthedocs.io/
  dev_url: https://github.com/python-trio/trio-asyncio

extra:
  recipe-maintainers:
    - scopatz
    - dhirschfeld
