travis:
  secure:
    BINSTAR_TOKEN: GtVtFJKrf/s/gYUhc/iryWk1+FUG+x8y5eUqL73b9/fMJJwdoDyaC/D4r2dAu9sgdOw7k6E5OZB9730EEYLvhPyCaqPdJ7r2AVxr03rMoM1kOADsj18EzqcwZEGD+NFJDX1Fq+l0myamSxA8O3i9OofLnDcVCTyQoJbeaenJBLEIHWoR3tGTDhbmYzNjKhugIrAOACmWhO/GWSGdUHYI5M17J/wyt5OtXHMIWHyHpn9OdfRSB8A5rxQnX6w54lD200ekVS6YU3Q8y5ZQ6xmxth2a4cMVaUiUxafKDAYZJPQcVHVWjXJohlK/2S5k+2ntUdpQN251L/4KsDSjzOmlDwL3UaxDpgifrtEfass0TVu/yAv1k0zn2XBvzvLuH26y9msq0kNmSSO3iCETfqsQ9O72E3IPDsizKm2VuCVwrGRD25y8aJGqBEc9Qj1URO9hw2ywtnEyd84zPs9LCo7IJOgZ69PHX8lYiYQiNPszXGQwmZtjqCB50mf2nCq0ScV+h9PwlLyy+haGI2Gw85YpWtfur1C8eHCzIP5dB2oeZOR4Pck007GJlqEEnDx0iOVGU0fYxX4bl2b5Z9aCHdU/7xO01pYcHlWe0yHD0U9XYdqs87oU43LZcCCJIicPLJcO2ywqU1yqzfVlpNGpzPFLrZ7HVeVBOpb4KH2JqVBYJ9k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
